export const tags = {
  colors: [
    { title: "Blue", color: "#3da5ff" },
    { title: "Teal", color: "#00b9a8" },
    { title: "Mint", color: "#83f3b8" },
    { title: "Green", color: "#74dc2e" },
    { title: "Sage", color: "#afbf8d" },
    { title: "Yellow", color: "#ffe272" },
    { title: "Beige", color: "#f1d299" },
    { title: "Brown", color: "#986a33" },
    { title: "Orange", color: "#ff9351" },
    { title: "Peach", color: "#eba39c" },
    { title: "Red", color: "#ff3737" },
    { title: "Maroon", color: "#a72626" },
    { title: "Pink", color: "#ff74bc" },
    { title: "Purple", color: "#bf51e0" },
    { title: "Navy", color: "#414796" },
    { title: "Black", color: "#333" },
    { title: "Grey", color: "#dcdcdc" },
    { title: "White", color: "#fff" },
  ],
  collections: [
    "Pastel",
    "Vintage",
    "Retro",
    "Neon",
    "Gold",
    "Light",
    "Dark",
    "Warm",
    "Cold",
    "Summer",
    "Fall",
    "Winter",
    "Spring",
    "Happy",
    "Nature",
    "Earth",
    "Night",
    "Space",
    "Rainbow",
    "Gradient",
    "Sunset",
    "Sky",
    "Sea",
    "Kids",
    "Skin",
    "Food",
    "Cream",
    "Coffee",
    "Wedding",
    "Christmas",
    "Halloween",
  ],
};

export type Tags = typeof tags;
